name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  token_scanning:
    runs-on: ubuntu-latest
    needs: test  # This job will run after the test job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run token scanning
        run: |
          # Replace with your token scanning command
          echo "Running token scanning..."
          # Example command: ./token-scanner --path . 